import { OvertimeEntry, StaffMember } from './types';

export const INITIAL_AHMAD_ENTRIES: OvertimeEntry[] = [
  {
    id: 'ot-1',
    date: '2024-10-02',
    startTime: '18:00',
    endTime: '21:30',
    duration: 3.5,
    project: 'Siaran Langsung Buletin Utama (TV3)',
    notes: 'Penyelenggaraan kecemasan video switcher & sambungan satelit MCR Sri Pentas semasa siaran langsung Buletin Utama',
    attachmentName: 'Borang_Pengesahan_OT_TV3_02Okt.pdf',
    attachmentSize: '245 KB',
    attachmentType: 'pdf',
  },
  {
    id: 'ot-2',
    date: '2024-10-04',
    startTime: '19:00',
    endTime: '23:00',
    duration: 4.0,
    project: 'Penerbitan Siaran Luar OB Van (Primeworks)',
    notes: 'Kawalan teknikal gentian optik dan audio pemancar OB Van di Stadium Nasional sempena perlawanan Liga Super',
    attachmentName: 'Kelulusan_Khas_Penerbit_OBVan_04Okt.pdf',
    attachmentSize: '318 KB',
    attachmentType: 'pdf',
  },
  {
    id: 'ot-3',
    date: '2024-10-06',
    startTime: '14:00',
    endTime: '17:00',
    duration: 3.0,
    project: 'Penyelenggaraan Pemancar & MCR Sri Pentas',
    notes: 'Siaga ujian sandaran (redundancy failover) pemancar frekuensi penyiaran Sri Pentas hujung minggu',
    attachmentName: 'Surat_Arahan_Tugas_SriPentas_06Okt.png',
    attachmentSize: '512 KB',
    attachmentType: 'image',
  },
];

export const INITIAL_OTHER_STAFF: StaffMember[] = [
  {
    id: 'MPB-2041',
    name: 'Nurul Izzati',
    department: 'Bilik Berita & Hal Ehwal Semasa (TV3)',
    role: 'Wartawan Penyiaran Kanan',
    status: 'Submitted',
    submittedAt: '2024-10-06 14:15',
    avatar: 'NI',
    entries: [
      {
        id: 'ni-1',
        date: '2024-10-01',
        startTime: '18:00',
        endTime: '22:00',
        duration: 4.0,
        project: 'Liputan Sidang Parlimen Dewan Rakyat',
        notes: 'Liputan khas perbahasan rang undang-undang bajet & wawancara eksklusif',
      },
      {
        id: 'ni-2',
        date: '2024-10-03',
        startTime: '18:00',
        endTime: '21:30',
        duration: 3.5,
        project: 'Siaran Langsung Buletin Utama (TV3)',
        notes: 'Penyediaan laporan khas siaran langsung berita utama jam 8 malam',
      },
      {
        id: 'ni-3',
        date: '2024-10-05',
        startTime: '18:00',
        endTime: '22:30',
        duration: 4.5,
        project: 'Liputan Khas & Berita Tergempar (Bilik Berita MPB)',
        notes: 'Penugasan kecemasan sidang media khas kementerian & liputan langsung',
      },
    ],
  },
  {
    id: 'MPB-3092',
    name: 'Khairul Anuar',
    department: 'Unit Siaran Luar (OB Van) & Primeworks',
    role: 'Ketua Jurukamera Siaran Luar',
    status: 'Pending',
    submittedAt: null,
    avatar: 'KA',
    entries: [
      {
        id: 'ka-1',
        date: '2024-10-02',
        startTime: '17:30',
        endTime: '21:00',
        duration: 3.5,
        project: 'Penerbitan Siaran Luar OB Van (Primeworks / Stadium)',
        notes: 'Siaga jurukamera utama padang bagi siaran langsung perlawanan bola sepak',
      },
      {
        id: 'ka-2',
        date: '2024-10-04',
        startTime: '18:00',
        endTime: '21:00',
        duration: 3.0,
        project: 'Penerbitan Drama & Program Hiburan (TV3 / TV9)',
        notes: 'Penggambaran luar waktu malam untuk program hiburan Primeworks',
      },
    ],
  },
  {
    id: 'MPB-1184',
    name: 'Siti Sarah',
    department: 'Media Prima Audio (Hot FM & Fly FM)',
    role: 'Penerbit Eksekutif Siaran Radio',
    status: 'Submitted',
    submittedAt: '2024-10-05 09:12',
    avatar: 'SS',
    entries: [
      {
        id: 'ss-1',
        date: '2024-10-02',
        startTime: '05:30',
        endTime: '08:30',
        duration: 3.0,
        project: 'Penerbitan & Konsert Khas Media Prima Audio (Hot FM / Fly FM)',
        notes: 'Siaga awal pagi siaran langsung Bekpes Hot & lintas langsung luar studio',
      },
      {
        id: 'ss-2',
        date: '2024-10-04',
        startTime: '18:00',
        endTime: '22:30',
        duration: 4.5,
        project: 'Penerbitan & Konsert Khas Media Prima Audio (Hot FM / Fly FM)',
        notes: 'Pengurusan artis & penyiaran konsert akustik live Hot FM di Sri Pentas',
      },
      {
        id: 'ss-3',
        date: '2024-10-06',
        startTime: '18:00',
        endTime: '22:00',
        duration: 4.0,
        project: 'Penerbitan & Konsert Khas Media Prima Audio (Hot FM / Fly FM)',
        notes: 'Sokongan penyiaran jelajah radio Hot FM hujung minggu',
      },
    ],
  },
  {
    id: 'MPB-4520',
    name: 'Marcus Wong',
    department: 'REV Media Group & Tonton',
    role: 'Ketua Pereka Grafik Siaran & Video',
    status: 'Pending',
    submittedAt: null,
    avatar: 'MW',
    entries: [
      {
        id: 'mw-1',
        date: '2024-10-01',
        startTime: '18:00',
        endTime: '21:00',
        duration: 3.0,
        project: 'Pembangunan Portal Berita & Penstriman Tonton (REV Media)',
        notes: 'Penyediaan aset motion graphics promo Anugerah Juara Lagu (AJL) untuk aplikasi Tonton',
      },
    ],
  },
  {
    id: 'MPB-5831',
    name: 'Farah Nabilah',
    department: 'Penerbitan Hiburan & Kandungan TV3',
    role: 'Penolong Penerbit Rancangan',
    status: 'Submitted',
    submittedAt: '2024-10-06 17:30',
    avatar: 'FN',
    entries: [
      {
        id: 'fn-1',
        date: '2024-10-03',
        startTime: '18:00',
        endTime: '22:00',
        duration: 4.0,
        project: 'Penerbitan Drama & Program Hiburan (TV3 / TV9)',
        notes: 'Rakaman studio Muzik-Muzik episod mingguan di Studio 1 Sri Pentas',
      },
      {
        id: 'fn-2',
        date: '2024-10-05',
        startTime: '18:00',
        endTime: '22:00',
        duration: 4.0,
        project: 'Penerbitan Drama & Program Hiburan (TV3 / TV9)',
        notes: 'Penyelarasan bakat dan suntingan pasca siaran drama Akasia',
      },
    ],
  },
];

export const PROJECT_OPTIONS = [
  'Siaran Langsung Buletin Utama (TV3)',
  'Liputan Khas & Berita Tergempar (Bilik Berita MPB)',
  'Penerbitan Siaran Luar OB Van (Primeworks / Stadium)',
  'Penyelenggaraan Pemancar & MCR Sri Pentas',
  'Penerbitan & Konsert Khas Media Prima Audio (Hot FM / Fly FM)',
  'Penerbitan Drama & Program Hiburan (TV3 / TV9)',
  'Pasca Produksi Grafik & Promo Penyiaran (8TV / TV3)',
  'Pembangunan Portal Berita & Penstriman Tonton (REV Media)',
  'Liputan Sidang Parlimen Dewan Rakyat',
  'Penugasan Teknikal & Siaga Penyiaran Hujung Minggu',
];
